### PR TITLE
add(ci): GitHub workflow to package plugin on CI/CD

### PR DESCRIPTION
**Pull request by Guts**
To be merged after https://github.com/WhereGroup/profile-manager/pull/21

In this PR, a GitHub workflow to:

- package the plugin on every PR where plugin's files have been modified
- release it as GitHub Release
- publish it automatically to official QGIS repository (see below)

@kannes to make the workflow work, you have to set your plugins.qgis.org credentials as GitHub Actions Secrets (`OSGEO_PASSWORD` and `OSGEO_USER`). Screenshot from [QTribu](https://github.com/geotribu/qtribu):

image
 
----

- Related to https://github.com/WhereGroup/profile-manager/issues/10
- :heart: Funded by [Oslandia](https://oslandia.com/) and [ANFSI](https://www.linkedin.com/company/anfsi/about/).

### CODE REVIEW

**Comment by kannes** [comment]
Oh nice! Tbh we do not have a technical account for this yet but all our plugins are maintained by different people and their accounts... Is there a standard process that you can recommend? Does OSGeo allow technical accounts? I'd like to not use my personal account for this.

**Comment by Guts** [comment]
We use the `oslandia` account at Oslandia and the `geotribu` account at Geotribu but TBH it's not so important I think, personal account is OK. Iwas using it for QTribu until recently. You just need to use credentials of an user who is authorized to publish a new version of the plugin (owner or maintainer level on <https://plugins.qgis.org>).

For a few months, API token are available but it's still not supported in QGIS Plugin CI (https://github.com/opengisch/qgis-plugin-ci/issues/285).

**Review by jmkerloch — APPROVED** [review]
Again every thing looks OK to me :rocket:

**Comment by kannes** [comment]
I have set up the secrets with my personal account for now and switch to the technical account once we have it.

**Pull request merged**
